### ISSUE TITLE
Does not fully boot vanila

### ISSUE THREAD

**Issue by karabas2011** [darkspr1te/mkstft35_V1_open_bootloader#1]
I compiled and flashed bootloader
then compiled firmware, renamed it to mkslcd.bin
copied [font] and [bmp] folders and config.ini from your folder.
 
It tries to boot but black screen. And I didnot see BMPs flashing.

Stock mkstft35.bin boots successfully without renaming to .CUR

Sorry, I removed sdcard and it boots to white sceen with calibration point (left up corner) and some garbage.
Next I removed msklcd.bin leaving only config.ini and reboot with sdcard - black screen
Next I tried empty sdcard - black screen
 
![mks](https://user-images.githubusercontent.com/2634978/92921565-ed9e2180-f43c-11ea-9c7e-69ac8267ca72.jpg)

**Comment by darkspr1te** [comment]
make sure the fonts/bmp are in a folder called MKS , i can see from the image above it's not yet written the fonts so you wont see any text

**Comment by karabas2011** [comment]
What exactly MKS folder I need to copy?
I already tried MKS from bigtreetech-touchscreen-firmware-master/Copy to sdcard root directory to update/MKS
with pics 70x70 pixels

So my dir looks like:
MKS/  (with font/ and bmp/)
mkslcd.bin
config.ini

**Comment by darkspr1te** [comment]
that looks correct, the mkslcd.bin , what is it's source (if it is from my BTT repo did you select [env:MKS_35_V1_0] build ? ) , i can post a verified working build as a test , see if it works on your device.

**Comment by karabas2011** [comment]
[platformio]
src_dir      = TFT
boards_dir   = buildroot/boards
;Build only Target - BIGTREE_TFT35_V3_0
default_envs = MKS_35_V1_0

Yes it will be good to try your binary
BTW in MKS folder no large_byte_ascii.fon file. Does it need to be?

**Comment by darkspr1te** [comment]
Here you go, 
[mkslcd.zip](https://github.com/darkspr1te/mkstft35_V1_open_bootloader/files/5210339/mkslcd.zip)
A quick tip, you can select which one to build at the bottom of platformio there is a Icon with "Default" next to it, you can select MKSTFT35V1_0 from there to build and not have to edit the platformio.ini 
![image](https://user-images.githubusercontent.com/3225653/92950263-ac1d6e80-f45c-11ea-853d-193595a2030f.png)
change to 
![image](https://user-images.githubusercontent.com/3225653/92950294-b8093080-f45c-11ea-9d54-4f370454a32e.png)
darkspr1te

**Comment by karabas2011** [comment]
What files and its sizes in your MKS/fonts?
Yor file tries to boot but garbage fonts. It loads pics
It boots but incorrect pics and fonts
![mks2](https://user-images.githubusercontent.com/2634978/92951024-62398600-f466-11ea-8f0c-b1926e96077b.jpg)
![mks1](https://user-images.githubusercontent.com/2634978/92951028-636ab300-f466-11ea-8d85-efe6d83ea922.jpg)

**Comment by darkspr1te** [comment]
[MKS.zip](https://github.com/darkspr1te/mkstft35_V1_open_bootloader/files/5210445/MKS.zip)
try this, from my sd card

**Comment by darkspr1te** [comment]
the font/files for this model are in TFT35 folder , the mks folder present is for the mks32" , i need to do a pull req to change that , it was before i decided to port btt to all mks devices, it was assumed that would be the only model.

**Comment by karabas2011** [comment]
It works! Loading fonts and pics
Now I need to find how to compile working binary.
calibrating touchscreen is perfect

but after several boots it hangs showing Logo.

**Comment by darkspr1te** [comment]
Ok, i suspect that issue is due to the I2C chip , i've found it hangs when addressed sometimes after a reset of the device, i need to add a full "I2C reset routine" to combat that. edit out #define I2C_EEPROM in pin_MKS_TFT35_V1_0.h to switch to using stm's eeprom emulation (internal flash) for storing settings.

**Comment by karabas2011** [comment]
And your binary size differs from mine. It means the code is different or platformio

**Comment by darkspr1te** [comment]
Main issue of non boot is resolved, will close this issue now.
