### ISSUE TITLE
Inserted SDcard causes hanging after flashing/booting

### ISSUE THREAD

**Issue by karabas2011** [darkspr1te/mkstft35_V1_open_bootloader#2]
I compiled fimrware with commented out I2C_EEPROM.
It loads and hangs. If I remove sdcard it boots and I see it's actually new firmware.
But with sdcard ( even empty) it hangs.
Your firmware.bin works perfectly. 
Is your github branch synchronized with  local one?

**Comment by karabas2011** [comment]
Warnings:
```
Compiling .pio\build\MKS_35_V1_0\src\src\User\Hal\stm32f2_f4xx\spi_slave.o
In file included from TFT\src\User\Hal\stm32f2_f4xx\i2c_eeprom.c:10:0:
TFT\src\User\Hal\stm32f2_f4xx\i2c_eeprom.h:47:44: warning: "/*" within comment [-Wcomment]
 #define EEPROM_MAX_SIZE             0x2000 /* 64Kbit*/
                                             
TFT\src\User\Hal\stm32f2_f4xx\i2c_eeprom.c: In function 'I2C_Write':
TFT\src\User\Hal\stm32f2_f4xx\i2c_eeprom.c:196:24: warning: pointer targets in passing argument 3 of 'GUI_DispString' differ in signedness [-Wpointer-sign]
   GUI_DispString(200,0,"large byte write");
                        ^~~~~~~~~~~~~~~~~~
In file included from TFT\src\User\API/menu.h:10:0,
                 from TFT\src\User\API/Colors.h:10,
                 from TFT\src\User/includes.h:19,
                 from TFT\src\User\Hal\stm32f2_f4xx\i2c_eeprom.h:3,
                 from TFT\src\User\Hal\stm32f2_f4xx\i2c_eeprom.c:10:
TFT\src\User\API\UI/GUI.h:75:6: note: expected 'const uint8_t * {aka const unsigned char *}' but argument is of type 'char *'
 void GUI_DispString(int16_t x, int16_t y, const uint8_t *p);
      ^~~~~~~~~~~~~~
TFT\src\User\Hal\stm32f2_f4xx\i2c_eeprom.c:214:2: warning: label 'errReturn' defined but not used [-Wunused-label]
  errReturn:
  ^~~~~~~~~
TFT\src\User\Hal\stm32f2_f4xx\i2c_eeprom.c:171:19: warning: unused variable 'Timeout' [-Wunused-variable]
     __IO uint32_t Timeout = 0;
                   ^~~~~~~
TFT\src\User\Hal\stm32f2_f4xx\i2c_eeprom.c: In function 'EEPROM_ReadBuffer':
TFT\src\User\Hal\stm32f2_f4xx\i2c_eeprom.c:291:16: warning: comparison between pointer and integer
  for (int i=0;i<NumByteToRead;i++)
                ^
TFT\src\User\Hal\stm32f2_f4xx\i2c_eeprom.c: In function 'EEPROM_FlashRead':
TFT\src\User\Hal\stm32f2_f4xx\i2c_eeprom.c:322:27: warning: passing argument 3 of 'EEPROM_ReadBuffer' makes pointer from integer without a cast [-Wint-conversion]
  EEPROM_ReadBuffer(data,0,len);
                           ^~~
TFT\src\User\Hal\stm32f2_f4xx\i2c_eeprom.c:273:6: note: expected 'uint16_t * {aka short unsigned int *}' but argument is of type 'u32 {aka long unsigned int}'
 void EEPROM_ReadBuffer(uint8_t* pBuffer, uint16_t ReadAddr, uint16_t* NumByteToRead)
      ^~~~~~~~~~~~~~~~~
Compiling .pio\build\MKS_35_V1_0\src\src\User\Hal\stm32f2_f4xx\timer_pwm.o
Compiling .pio\build\MKS_35_V1_0\src\src\User\Hal\stm32f2_f4xx\uart.o
Compiling .pio\build\MKS_35_V1_0\src\src\User\Hal\sw_spi.o
TFT\src\User\Hal\stm32f2_f4xx\sdio_sdcard.c:309:0: warning: "NULL" redefined
 #define NULL 0
 
In file included from c:\users\admin\.platformio\packages\toolchain-gccarmnoneeabi@1.70201.0\arm-none-eabi\include\string.h:17:0,
                 from TFT\src\User\Hal\stm32f2_f4xx\sdio_sdcard.c:229:
c:\users\admin\.platformio\packages\toolchain-gccarmnoneeabi@1.70201.0\lib\gcc\arm-none-eabi\7.2.1\include\stddef.h:406:0: note: this is the location of the previous definition
 #define NULL ((void *)0)
 
TFT\src\User\Hal\stm32f2_f4xx\sdio_sdcard.c: In function 'SD_ReadDisk':
TFT\src\User\Hal\stm32f2_f4xx\sdio_sdcard.c:3101:7: warning: this 'while' clause does not guard... [-Wmisleading-indentation]
       while(SD_GetStatus() != SD_TRANSFER_OK);
       ^~~~~
TFT\src\User\Hal\stm32f2_f4xx\sdio_sdcard.c:3103:4: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'while'
    memcpy(buf,SDIO_DATA_BUFFER,512);
    ^~~~~~
TFT\src\User\Hal\stm32f2_f4xx\sdio_sdcard.c: In function 'SD_WriteDisk':
TFT\src\User\Hal\stm32f2_f4xx\sdio_sdcard.c:3145:7: warning: this 'while' clause does not guard... [-Wmisleading-indentation]
       while(SD_GetStatus() != SD_TRANSFER_OK);
       ^~~~~
TFT\src\User\Hal\stm32f2_f4xx\sdio_sdcard.c:3147:4: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'while'
    buf+=512;
    ^~~
Compiling .pio\build\MKS_35_V1_0\src\src\User\Hal\w25qxx.o
Compili
```

**Comment by karabas2011** [comment]
I defined #define SD_POLLING_MODE 
Now it boots. 
But my binary size(212524) still less than yours(218940)
Cannot flash with MKS/ folder - hangs with garbage font. Only with MKS.cur

**Comment by darkspr1te** [comment]
can you post your compiled bin file and if possible your elf file from .pio/build/MKS_35_V1_0/MKSTFT35_V1_0.26.X (the python file buildroot/scripts/custom_filename.py renames the build file so the elf extension is left out) 
on the bootloader side I messed up, i pushed a very very old build to the system, i need to refactor it and push the correct build with file rename, error checking and more features baked in.

**Comment by karabas2011** [comment]
[MKS_35_V1_0.ZIP](https://github.com/darkspr1te/mkstft35_V1_open_bootloader/files/5218881/MKS_35_V1_0.ZIP)
It is with sd_poling_mode enable
I can post with DMA version

**Comment by darkspr1te** [comment]
please also post dma version, many thanks

**Comment by karabas2011** [comment]
[MKS_35_V1_0.ZIP](https://github.com/darkspr1te/mkstft35_V1_open_bootloader/files/5218942/MKS_35_V1_0.ZIP)
DMA

**Comment by karabas2011** [comment]
#define I2C_EEPROM is commented out
I can enable it and rebuild.
Please send me your src/ folder

**Comment by darkspr1te** [comment]
The files online in my BTT repo are the latest i'am using, but i will post a zip of the folder.

**Comment by darkspr1te** [comment]
seems i cant paste files here larger than 10mb and the repo files are 15mb+ let me find another way to post them,

**Comment by karabas2011** [comment]
only src/  is about 2Mb zip
or via email

**Comment by karabas2011** [comment]
Is your screen calibration linear?
I many times recalibrate but in Terminal can hardly press 7-8-9 row ( top and bottom rows are good)
and colomn M X Z S. 
I  tried different positions of  center point, seems no effect at all

**Comment by darkspr1te** [comment]
My screen calibration is way off, it's listed as a bug, for some reason the math for the lcd touch is off and I'am not sure why, they did improve it in a recent patch (before i could not even calibrate) but it still needs work , i have a alternate driver i might try, it has hard coded numbers instead of calibration and i've found it to work great in the past. i will also post the src files when i get back from the office. crazy day today.

**Comment by karabas2011** [comment]
Can MKS driver code help?

**Comment by darkspr1te** [comment]
> Can MKS driver code help?

sadly not, its code is so over the place that it's not compatible with this code base, it would be quicker to start from scratch.  but i'am working on it.

**Comment by darkspr1te** [comment]
[btt-mkstft.zip](https://github.com/darkspr1te/mkstft35_V1_open_bootloader/files/5226403/btt-mkstft.zip)
btt source as promised but it should be same as the github repo as i push files back every day, not sure why you're getting different file sizes unless my debug code has something to do with it.

**Comment by karabas2011** [comment]
No. your github repo is 5 days old.
Your posted code is different. Firmware.bin more large in size. 
It works immediatly after flashing (without loading config.ini). 
My config.ini is  loading with 3 new invalids insteed of one( yours), than hangs.
Reboot (without sdcard or without firmware.bin) shows blackscreen. I am able to use compiled firmware only flashing it every boot.
I am testing on two displays

**Comment by darkspr1te** [comment]
I am no sure why my repo is showing 5 days old when i'am pushing almost every night.Could you check to see if my latest commits are pushed and public , am using the master branch (i see there is a 0.26.1.x branch, not sure if thats new features branch or not but i'ave stuck to master for my commits and patches) 
https://github.com/darkspr1te/BIGTREETECH-TouchScreenFirmware.git

**Comment by darkspr1te** [comment]
please note for the latest build you will get a error on boot up, "out dated config, please update" , all you need to sort this is add config.ini and the TFT35 folder to sd card, rename the unified TFT35 folder to MKS when on SD card and the device will update and boot normally.

**Comment by karabas2011** [comment]
Now I see github updated
Compiled firmware boots and works!
Waiting for screen calibration fix.
And no sound currently.

**Comment by darkspr1te** [comment]
sound can be enabled by removing the comment-out in pin_MKS_TFT35V1_0.h , line 142 
//#define BUZZER_PIN    PA2

**Comment by karabas2011** [comment]
Currently all preheat temps are 0 or 1

**Comment by karabas2011** [comment]
I think this issue can be closed but where is right place to chat bugs?

**Comment by darkspr1te** [comment]
bugs for BTT firmware can be either my repo or the origin BTT repo, prob best on original BTT repo as more will see it and assist , especially if it's not hardware code related but more to do with actual firmware function.

**Comment by karabas2011** [comment]
Ok, but they need to commit your PR?
